Fork and Clone a Repository
python-geeks/Automation-scripts pull request #323
Opened 2020-10-22 07:54 UTC by Remakh

# Pull Request Template

**script name** - Fork and Clone

**A script that forks and clones a repository onto your device, made using PyGithub.**

### Issue no.(must) - #319 

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

2020-10-22 08:30 UTC, m4dummies commented
Hi @Remakh  are u having problems with linter?

2020-10-22 09:28 UTC, Remakh commented
> Hi @Remakh are u having problems with linter?

I had some issues but I got it in the end.

2020-10-22 11:05 UTC, Sacrezar requested changes
Hey, thank you for your contribution. Here is my review:

Forking is working great but you'll have to change your way to authenticate, see: https://developer.github.com/changes/2020-02-14-deprecating-password-auth/

There is some issue as for the cloning, I have the following error:
```ERROR: clone() takes 1 positional argument but 2 were given```

If you can, it would be interesting to allow the user to choose between SSH or http connexion when cloning. 

It is not an obligation but it could be cool to let the user hardcode his token, the default path and the default way to clone (ssh, http or git cli). Either hardcode it or store it in a json file.
That way, it opens the possibility to do something like that:
```
To fork into your account:
py Fnc.py python-geeks/Automation-scripts

To fork into your organization:
py Fnc.py python-geeks/Automation-scripts my_organization
```
See sys.argv [here](https://docs.python.org/3/library/sys.html#sys.argv) and [there](https://www.geeksforgeeks.org/how-to-use-sys-argv-in-python/).

For the requirements.txt, could you just do these little changes please? 
* Remove `git = 2.20.0`
* Change `PyGithub = 1.5.3` for `PyGithub == 1.53` or just `PyGithub`

2020-10-22 11:08 UTC, Remakh commented
> Hey, thank you for your contribution. Here is my review:
> 
> Forking is working great but you'll have to change your way to authenticate, see: https://developer.github.com/changes/2020-02-14-deprecating-password-auth/
> 
> There is some issue as for the cloning, I have the following error:
> `ERROR: clone() takes 1 positional argument but 2 were given`
> 
> If you can, it would be interesting to allow the user to choose between SSH or http connexion when cloning.
> 
> It is not an obligation but it could be cool to let the user hardcode his token, the default path and the default way to clone (ssh, http or git cli). Either hardcode it or store it in a json file.
> That way, it opens the possibility to do something like that without any other interaction needed:
> 
> ```
> To fork into your account:
> py Fnc.py python-geeks/Automation-scripts
> 
> To fork into your organization:
> py Fnc.py python-geeks/Automation-scripts my_organization
> ```
> 
> See sys.argv [here](https://docs.python.org/3/library/sys.html#sys.argv) and [there](https://www.geeksforgeeks.org/how-to-use-sys-argv-in-python/).
> 
> For the requirements.txt, could you just do these little changes please?
> 
> * Remove `git = 2.20.0`
> * Change `PyGithub = 1.5.3` for `PyGithub == 1.53` or just `PyGithub`

Thanks for all your suggestions! I'll try to implement them and make the changes

2020-10-22 11:39 UTC, Sacrezar commented
No worries.

If you have any problem with flake8 linting, you can install it via 
```
py -m pip install flake8
```
and run it like this:
```
py -m flake8 my_file.py
```

Alternatively, if you're using vscode, you can change your linter from pylint to flake8.
CTRL SHIFT P and write linter. 
![image](https://user-images.githubusercontent.com/38185428/96866597-d276f680-146b-11eb-91fc-6f977b5df9bf.png)
![image](https://user-images.githubusercontent.com/38185428/96866718-fcc8b400-146b-11eb-9828-3a058ccca8a8.png)

2020-10-22 14:11 UTC, pawangeek requested changes

2020-10-22 14:11 UTC, pawangeek commented on fork_and_clone/Fnc.py
> +
Add docstring about input args

2020-10-22 14:11 UTC, pawangeek commented on fork_and_clone/Fnc.py
> +
Here too

2020-10-22 15:55 UTC, Remakh commented on fork_and_clone/Fnc.py
> +
Sure will do

2020-10-24 17:42 UTC, pawangeek approved these changes

2020-10-24 17:43 UTC, merged