Added Simple Plagiarism Checker
python-geeks/Automation-scripts pull request #324
Opened 2020-10-22 18:17 UTC by abhinand5

# Simple Plagiarism Checker

**script name** - simple-plagiarism-checker.py

**Brief about script**
Implemented a simple plagiarism calculator. It compares two separate text files and gives a similarity score as an output. 

### Issue no.(must) - #181 

### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in proper folder (Name of folder should be in lowercase with no space in between)
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I have added README.md and requirements.txt with my script

If issue was not assigned to you Please don't make a PR. It will marked as invalid.

2020-10-23 15:15 UTC, pawangeek requested changes
First things first

1. It should assign 1.00 or raise an error if both files are empty

![error1](https://user-images.githubusercontent.com/42181691/97020967-db50f080-156f-11eb-831a-12e1f82ea814.PNG)

2. Round off to two decimal points. Here is the reason for that

![error2](https://user-images.githubusercontent.com/42181691/97021218-2f5bd500-1570-11eb-8098-59d58c2742d5.PNG)

3. And what should be the output of this

![error3](https://user-images.githubusercontent.com/42181691/97021535-94172f80-1570-11eb-955e-284e0673bc20.PNG)

2020-10-24 17:32 UTC, abhinand5 commented
Hi, I have made the recommended changes. Not sure what the `Greetings / greeting (pull_request_target)` that is failing, is that an issue?

2020-10-24 17:39 UTC, pawangeek commented
Yeah, there is some problem with automated actions. I will try to resolve that tomorrow and now it seems perfect @abhinand5

2020-10-24 17:40 UTC, pawangeek approved these changes

2020-10-24 17:40 UTC, merged